export * from './Login/LoginPage'
export * from './AddEmployee/AddEmployeePage'
export * from './Registration/RegisterPage'
export * from './NotFound/NotFoundPage'
export * from './Home/HomePage'
export * from './Employees/Employees'
